- .gitignore
- CHANGELOG.md
- Jenkinsfile
- README.md
- SpringBootExample/build-sampleapp-image.sh
- SpringBootExample/start_enterprise
- build-package.sh
- mvn-settings.xml
- pom.xml
- publish.sh
- secrets.yml
- tools.Dockerfile
The PR adds code signing to the pipeline, and publication of packages
to maven central as part of a release promotion.
> Code Signing and Publish to Maven Central

- Jenkinsfile
The tools image is required for building
the package.
> Build tools image during promotion

- README.md
- src/main/java/com/cyberark/conjur/springboot/annotations/ConjurPropertySource.java
- src/main/java/com/cyberark/conjur/springboot/annotations/ConjurValue.java
- src/main/java/com/cyberark/conjur/springboot/constant/ConjurConstant.java
> UAT review.

- README.md
> Proposed Spring Boot Plugin Changes from Leila

- pom.xml
Update Spring Boot to the latest version
- Increment the version of Spring Boot to the latest 2.6.6
changes, or
> Update Spring Boot Version

- CHANGELOG.md
Version numbers can't be reused for uploaded artifacts.  This will allow the full process to work for the initial release
- Increment version number for release promotion
changes, or
> Update version for initial release

- CHANGELOG.md
- README.md
Readme: Add latest version badge and links to version history, remove static version in maven dependency example. 
Changelog: Add next version in preparation for the next release.
> Update Readme and Changelog

- README.md
> Changed heading to Conjur OSS or Enterprise Setup

- README.md
Link directs to https://github.com/cyberark/community/blob/master/Conjur/conventions/certification-levels.md#certified …
> Updated the image link

- README.md
> hyperlink update under certification leve

- README.md
> Conjur Appliance URL - updated description

- README.md
> Added the note for Kubernetes users

- README.md
Confirmed with Maciek, and updated Conjur Enterprise from 5.0 to 12.5
merged.*
changes, or
> Technical Requirements Updated

- src/main/java/com/cyberark/conjur/springboot/core/env/ConjurPropertySource.java
Spring Boot Plugin makes multiple calls to Vault when fetching secrets.
-  Modified the existing code scenario. 
-  https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23323
CyberArk internal issue link: [insert issue ID]([ONYX-23323](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23323))
merged.*
changes, or
> ONYX-23323 | Spring Boot Plugin makes multiple calls to Vault when fetching secrets.

- SpringBootExample/pom.xml
- pom.xml
Update spring-boot-starter-parent to latest release 2.7.3
Update pom.xml spring-boot-starter-parent dependency.
Ensure the project is successfully built.
https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur-spring-boot-sdk/detail/SecurityUpdatesPom/3/pipeline 
changes, or
- [X ] No behavior was changed with this PR
> Update spring boot starter dependencies to latest release

- ConjurSpringCloudPluginTest/src/main/java/com/cyberark/conjur/plugintest/ConjurSpringCloudPluginTest.java
- ConjurSpringCloudPluginTest/src/main/resources/conjur.properties
- spring-boot-sdk-1.1/src/main/java/com/cyberark/conjur/springboot/config/ConjurAuthConfiguration.java
- spring-boot-sdk-1.1/src/main/java/com/cyberark/conjur/springboot/core/env/ConjurPropertySource.java
- spring-boot-sdk-1.1/src/main/java/com/cyberark/conjur/springboot/processor/ConjurValueProcessor.java
- spring-boot-sdk-1.1/src/main/java/com/cyberark/conjur/springboot/service/CustomPropertySourceChain.java
- spring-boot-sdk-1.1/src/main/java/com/cyberark/conjur/springboot/util/ConjurPropertySourceUtil.java
> Code Refactoring

- src/main/java/com/cyberark/conjur/springboot/annotations/ConjurValue.java
- src/main/java/com/cyberark/conjur/springboot/annotations/ConjurValues.java
- src/main/java/com/cyberark/conjur/springboot/processor/ConjurRetrieveSecretService.java
- src/test/resources/application.properties
Update with code climate fixex.
merged.*
changes, or
> Code Climate Fixes

- CHANGELOG.md
*Changelog updates for release.
*Changelog updates for release
merged.*
changes, or
> changelog updates for release

- CHANGELOG.md
- README.md
- src/main/java/com/cyberark/conjur/springboot/annotations/Registrar.java
- src/main/java/com/cyberark/conjur/springboot/constant/ConjurConstant.java
- src/main/java/com/cyberark/conjur/springboot/core/env/ConjurConfig.java
- src/main/java/com/cyberark/conjur/springboot/core/env/ConjurConnectionManager.java
- src/main/java/com/cyberark/conjur/springboot/core/env/ConjurPropertySource.java
- src/main/java/com/cyberark/conjur/springboot/processor/ConjurCloudProcessor.java
- src/main/java/com/cyberark/conjur/springboot/processor/ConjurRetrieveSecretService.java
- src/main/java/com/cyberark/conjur/springboot/processor/ConjurValueClassProcessor.java
- src/main/java/com/cyberark/conjur/springboot/processor/SpringBootConjurAutoConfiguration.java
- src/main/java/com/cyberark/conjur/springboot/service/CustomPropertySourceChain.java
- src/main/java/com/cyberark/conjur/springboot/service/DefaultPropertySourceChain.java
- src/main/java/com/cyberark/conjur/springboot/service/PropertyProcessorChain.java
- src/test/java/com/cyberark/conjur/springboot/ConjurPluginTests.java
- src/test/java/com/cyberark/conjur/springboot/core/env/ConjurConnectionManagerTest.java
- src/test/java/com/cyberark/conjur/springboot/core/env/ConjurPropertySourceTest.java
- src/test/java/com/cyberark/conjur/springboot/domain/ConjurPropertiesTest.java
- src/test/java/com/cyberark/conjur/springboot/processor/ConjurCloudProcessorTest.java
- src/test/java/com/cyberark/conjur/springboot/processor/ConjurRetrieveSecretServiceTest.java
- src/test/java/com/cyberark/conjur/springboot/service/CustomPropertySourceTest.java
- src/test/resources/application.properties
> merging the spring cloud code

- README.md
Updated documentation, to correct target `java` and `spring-boot` and `spring-cloud` versions.
Added documentation for `configuration properties`.
`README.md` updated.
merged.*
changes, or
> Documentation update for the next release

- Jenkinsfile
- SpringBootExample/start
Hopefully this will help debug intermittent problems in CI.
> Store container logs

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/cyberark/conjur/springboot/core/env/ConjurConnectionManager.java
> Version update

- CHANGELOG.md
- pom.xml
> Update pom.xml for v 1.8
